homepage: "https://github.com/anjpar/dvcp-safe-and-vulnerable"
language: c
primary_contact: "aparthas@outlook.com"
main_repo: "https://github.com/anjpar/dvcp-safe-and-vulnerable.git"
sanitizers:
  - address
  - undefined
  - memory
